name: release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release Notes
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          version: ${{ github.ref }}
      - name: Create Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.get_release_notes.outputs.release_notes }}
          draft: true
